application_id=b355fd7e10dad2566ffce301c1e7ee61
base_url_ship=https://api.worldofwarships.eu/wows/encyclopedia/ships
base_url_ship_prof=https://api.worldofwarships.asia/wows/encyclopedia/shipprofile
cu_src_dir=cusrc
ptx_dir=bin/cuda
cu_file_extension=.cu
cuh_file_extension=.cuh
ptx_file_extension=.ptx
vme_language=ja